"""Add initial_amount to Goal model

Revision ID: 06c2d739938b
Revises: 399919e2c920
Create Date: 2025-12-24 17:42:00.105448

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06c2d739938b"
down_revision = "399919e2c920"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "initial_amount", sa.Integer(), nullable=False, server_default="0"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_column("initial_amount")

    # ### end Alembic commands ###
