"""add rate_limits table

Revision ID: 249aa66e83e7
Revises: h1i2j3k4l5m6
Create Date: 2025-12-30 18:04:10.597301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "249aa66e83e7"
down_revision = "h1i2j3k4l5m6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rate_limits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rate_limits_key"), ["key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_rate_limits_timestamp"), ["timestamp"], unique=False
        )

    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_debts_deleted_at"))
        batch_op.create_index(
            batch_op.f("ix_debts_deleted_at"), ["deleted_at"], unique=False
        )

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_expenses_deleted_at"))
        batch_op.create_index(
            batch_op.f("ix_expenses_deleted_at"), ["deleted_at"], unique=False
        )

    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_goals_deleted_at"))
        batch_op.create_index(
            batch_op.f("ix_goals_deleted_at"), ["deleted_at"], unique=False
        )

    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_income_deleted_at"))
        batch_op.create_index(
            batch_op.f("ix_income_deleted_at"), ["deleted_at"], unique=False
        )

    with op.batch_alter_table("recurring_expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_recurring_expenses_deleted_at"))
        batch_op.create_index(
            batch_op.f("ix_recurring_expenses_deleted_at"), ["deleted_at"], unique=False
        )

    with op.batch_alter_table("subcategories", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_subcategory_user_category_name", ["user_id", "category", "name"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subcategories", schema=None) as batch_op:
        batch_op.drop_constraint("uq_subcategory_user_category_name", type_="unique")

    with op.batch_alter_table("recurring_expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recurring_expenses_deleted_at"))
        batch_op.create_index(
            batch_op.f("idx_recurring_expenses_deleted_at"),
            ["deleted_at"],
            unique=False,
        )

    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_income_deleted_at"))
        batch_op.create_index(
            batch_op.f("idx_income_deleted_at"), ["deleted_at"], unique=False
        )

    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_goals_deleted_at"))
        batch_op.create_index(
            batch_op.f("idx_goals_deleted_at"), ["deleted_at"], unique=False
        )

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expenses_deleted_at"))
        batch_op.create_index(
            batch_op.f("idx_expenses_deleted_at"), ["deleted_at"], unique=False
        )

    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_debts_deleted_at"))
        batch_op.create_index(
            batch_op.f("idx_debts_deleted_at"), ["deleted_at"], unique=False
        )

    with op.batch_alter_table("rate_limits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rate_limits_timestamp"))
        batch_op.drop_index(batch_op.f("ix_rate_limits_key"))

    op.drop_table("rate_limits")
    # ### end Alembic commands ###
