"""Initial schema

Revision ID: 96250a305e91
Revises: 
Create Date: 2025-12-17 18:38:33.461694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96250a305e91"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_name_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expense_name", sa.String(length=200), nullable=False),
        sa.Column("subcategory", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("expense_name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "credit_card_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credit_limit", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "debts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("original_amount", sa.Integer(), nullable=False),
        sa.Column("current_balance", sa.Integer(), nullable=False),
        sa.Column("monthly_payment", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "income",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("actual_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.create_index("idx_income_user_actual", ["user_id", "actual_date"], unique=False)
        batch_op.create_index(
            "idx_income_user_scheduled", ["user_id", "scheduled_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_income_actual_date"), ["actual_date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_income_scheduled_date"), ["scheduled_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_income_user_id"), ["user_id"], unique=False)

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "period_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("suggestion_type", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recurring_expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("subcategory", sa.String(length=100), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("frequency_value", sa.Integer(), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("day_of_week", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("next_due_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_fixed_bill", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salary_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("initial_debit_balance", sa.Integer(), nullable=False),
        sa.Column("initial_credit_balance", sa.Integer(), nullable=False),
        sa.Column("credit_limit", sa.Integer(), nullable=False),
        sa.Column("credit_budget_allowance", sa.Integer(), nullable=False),
        sa.Column("salary_amount", sa.Integer(), nullable=True),
        sa.Column("total_budget_amount", sa.Integer(), nullable=False),
        sa.Column("fixed_bills_total", sa.Integer(), nullable=False),
        sa.Column("remaining_amount", sa.Integer(), nullable=False),
        sa.Column("weekly_budget", sa.Integer(), nullable=False),
        sa.Column("weekly_debit_budget", sa.Integer(), nullable=False),
        sa.Column("weekly_credit_budget", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_defaults",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("default_expense_name", sa.String(length=200), nullable=True),
        sa.Column("default_category", sa.String(length=100), nullable=True),
        sa.Column("default_subcategory", sa.String(length=100), nullable=True),
        sa.Column("default_payment_method", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "budget_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("salary_period_id", sa.Integer(), nullable=True),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("budget_amount", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("period_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["salary_period_id"],
            ["salary_periods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("budget_periods", schema=None) as batch_op:
        batch_op.create_index(
            "idx_budget_period_active",
            ["user_id", "start_date", "end_date"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_budget_periods_end_date"), ["end_date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_budget_periods_start_date"), ["start_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_budget_periods_user_id"), ["user_id"], unique=False)

    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recurring_template_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("subcategory", sa.String(length=100), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.String(length=50), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("receipt_url", sa.String(length=500), nullable=True),
        sa.Column("is_fixed_bill", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recurring_template_id"],
            ["recurring_expenses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.create_index("idx_expense_user_category", ["user_id", "category"], unique=False)
        batch_op.create_index("idx_expense_user_date", ["user_id", "date"], unique=False)
        batch_op.create_index(
            "idx_expense_user_payment", ["user_id", "payment_method"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_expenses_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_expenses_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_expenses_payment_method"), ["payment_method"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_expenses_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expenses_user_id"))
        batch_op.drop_index(batch_op.f("ix_expenses_payment_method"))
        batch_op.drop_index(batch_op.f("ix_expenses_date"))
        batch_op.drop_index(batch_op.f("ix_expenses_category"))
        batch_op.drop_index("idx_expense_user_payment")
        batch_op.drop_index("idx_expense_user_date")
        batch_op.drop_index("idx_expense_user_category")

    op.drop_table("expenses")
    with op.batch_alter_table("budget_periods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_periods_user_id"))
        batch_op.drop_index(batch_op.f("ix_budget_periods_start_date"))
        batch_op.drop_index(batch_op.f("ix_budget_periods_end_date"))
        batch_op.drop_index("idx_budget_period_active")

    op.drop_table("budget_periods")
    op.drop_table("user_defaults")
    op.drop_table("salary_periods")
    op.drop_table("recurring_expenses")
    op.drop_table("period_suggestions")
    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_income_user_id"))
        batch_op.drop_index(batch_op.f("ix_income_scheduled_date"))
        batch_op.drop_index(batch_op.f("ix_income_actual_date"))
        batch_op.drop_index("idx_income_user_scheduled")
        batch_op.drop_index("idx_income_user_actual")

    op.drop_table("income")
    op.drop_table("debts")
    op.drop_table("credit_card_settings")
    op.drop_table("users")
    op.drop_table("expense_name_mappings")
    # ### end Alembic commands ###
