"""Add balance tracking fields to User model

Revision ID: 9ef3d960b257
Revises: j1k2l3m4n5o6
Create Date: 2026-01-05 16:34:02.005606

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ef3d960b257"
down_revision = "j1k2l3m4n5o6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("budget_periods", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_budget_periods_end_date"), ["end_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_periods_start_date"), ["start_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_periods_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("balance_start_date", sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "user_initial_debit_balance",
                sa.Integer(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "user_initial_credit_limit",
                sa.Integer(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "user_initial_credit_debt",
                sa.Integer(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "balance_mode",
                sa.String(length=20),
                nullable=False,
                server_default="sync",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("balance_mode")
        batch_op.drop_column("user_initial_credit_debt")
        batch_op.drop_column("user_initial_credit_limit")
        batch_op.drop_column("user_initial_debit_balance")
        batch_op.drop_column("balance_start_date")

    with op.batch_alter_table("budget_periods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_periods_user_id"))
        batch_op.drop_index(batch_op.f("ix_budget_periods_start_date"))
        batch_op.drop_index(batch_op.f("ix_budget_periods_end_date"))

    # ### end Alembic commands ###
