"""Add RecurringIncome model and payment_date_adjustment

Revision ID: b5f63ba537d4
Revises: 34eed8893f3a
Create Date: 2026-01-19 01:55:36.591772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f63ba537d4'
down_revision = '34eed8893f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('income_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_recurring_income_positive_amount'),
    sa.CheckConstraint('day_of_month IS NULL OR (day_of_month BETWEEN 1 AND 31)', name='check_recurring_income_day_of_month'),
    sa.CheckConstraint('day_of_week IS NULL OR (day_of_week BETWEEN 0 AND 6)', name='check_recurring_income_day_of_week'),
    sa.CheckConstraint('end_date IS NULL OR start_date < end_date', name='check_recurring_income_date_range'),
    sa.CheckConstraint('frequency_value IS NULL OR frequency_value > 0', name='check_recurring_income_frequency_value'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_income_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_income_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_income_recurring_income_id'), ['recurring_income_id'], unique=False)
        batch_op.create_foreign_key('fk_income_recurring_income_id', 'recurring_income', ['recurring_income_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date_adjustment', sa.String(length=20), nullable=False, server_default='exact_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('payment_date_adjustment')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint('fk_income_recurring_income_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_income_recurring_income_id'))
        batch_op.drop_column('recurring_income_id')

    with op.batch_alter_table('recurring_income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_income_deleted_at'))

    op.drop_table('recurring_income')
    # ### end Alembic commands ###
