"""add_currency_support

Revision ID: ed571c26be06
Revises: 06c2d739938b
Create Date: 2025-12-24 18:05:23.102267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed571c26be06"
down_revision = "06c2d739938b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("target_currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("rate > 0", name="check_exchange_rate_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "base_currency", "target_currency", "rate_date", name="uq_exchange_rate"
        ),
    )
    with op.batch_alter_table("exchange_rates", schema=None) as batch_op:
        batch_op.create_index(
            "idx_exchange_rate_lookup",
            ["base_currency", "target_currency", "rate_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exchange_rates_base_currency"),
            ["base_currency"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exchange_rates_rate_date"), ["rate_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exchange_rates_target_currency"),
            ["target_currency"],
            unique=False,
        )

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "currency", sa.String(length=3), nullable=False, server_default="EUR"
            )
        )
        batch_op.add_column(sa.Column("original_amount", sa.Integer(), nullable=True))

    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "currency", sa.String(length=3), nullable=False, server_default="EUR"
            )
        )
        batch_op.add_column(sa.Column("original_amount", sa.Integer(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "default_currency",
                sa.String(length=3),
                nullable=False,
                server_default="EUR",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("default_currency")

    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.drop_column("original_amount")
        batch_op.drop_column("currency")

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_column("original_amount")
        batch_op.drop_column("currency")

    with op.batch_alter_table("exchange_rates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exchange_rates_target_currency"))
        batch_op.drop_index(batch_op.f("ix_exchange_rates_rate_date"))
        batch_op.drop_index(batch_op.f("ix_exchange_rates_base_currency"))
        batch_op.drop_index("idx_exchange_rate_lookup")

    op.drop_table("exchange_rates")
    # ### end Alembic commands ###
