"""Add exchange_rate_used to expenses and income

Revision ID: f65eb8a43054
Revises: ed571c26be06
Create Date: 2025-12-25 15:11:38.850218

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f65eb8a43054"
down_revision = "ed571c26be06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("exchange_rate_used", sa.Float(), nullable=True))

    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.add_column(sa.Column("exchange_rate_used", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.drop_column("exchange_rate_used")

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_column("exchange_rate_used")

    # ### end Alembic commands ###
