"""Add account lockout fields to User model

Revision ID: faad44d4429e
Revises: 96250a305e91
Create Date: 2025-12-17 18:47:02.805427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "faad44d4429e"
down_revision = "96250a305e91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("failed_login_attempts", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("locked_until", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("locked_until")
        batch_op.drop_column("failed_login_attempts")

    # ### end Alembic commands ###
